### ISSUE TITLE
Error 401 while trying to synchronise Mangadex tracking

### ISSUE THREAD

**Issue by MrDfour** [jobobby04/TachiyomiSY#1019]
### Steps to reproduce

1. Go into any Manga
2. Open the Mangadex tracking
3. Click on the search result
4. Selection menu closes and error 401 pops up

### Expected behavior

Mangadex tracking should synchronise correctly 

### Actual behavior

Error 401 makes it unable to synchronise correctly, even manga manually introduced via mangadex webpage can't synchronise progress even if it does shows previously binded tracking
![Screenshot_20240115-151838_TachiyomiSY](https://github.com/jobobby04/TachiyomiSY/assets/103494853/ee1f4966-7ada-4207-8493-10bcf710833c)

### Tachiyomi version

1.10.1

### Android version

Android 13

### Device

Poco x3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Blackklegend** [comment]
That's because your token expired, log off and login again in trackers and it should be fixed

**Comment by MrDfour** [comment]
> That's because your token expired, log off and login again in trackers and it should be fixed

It works but the token expires in no more than half an hour. I think the issue arises when I use the option to bulk synchro stuff in TachiyomiSY to mangadex

**Comment by jobobby04** [comment]
Probably fixed
