### ISSUE TITLE
Myanimelist tracker login not working

### ISSUE THREAD

**Issue by swedishchicken** [jobobby04/TachiyomiSY#1061]
### Steps to reproduce

Try to login to Myanimelist tracker
Get infinite login refresh, or if cancelled a 403 error

### Expected behavior

Login with credentials and approve access to myanimelist

### Actual behavior

After entering my login credentials and clicking on continue, page just refreshes and i can enter credentials again. But in the end i never get logged in.

### Tachiyomi version

1.10.2

### Android version

android version 13

### Device

galaxy A14 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Poncow5** [comment]
Same with me same android version
Got this message
![1706539547287](https://github.com/jobobby04/TachiyomiSY/assets/72888366/9bebd969-80be-4172-b7fe-fe986ba82564)

**Comment by NeKoOuO** [comment]
jobobby didn't update the [v0.16.2](https://github.com/mihonapp/mihon/releases/tag/v0.16.2) yet so...just wait

**Comment by diggtrap** [comment]
Any updates on this? Switched phones and the backup had the right credentials but then it said I needed to relogin and now its giving me an infinite loading screen.

**Comment by dtantono** [comment]
yeah on Mihon, it said it solved. But, not on this fork

**Comment by Blackklegend** [comment]
preview r545 carried mihon's credentials, I think. So next build needs them to be revised, and possibly changed

**Comment by jobobby04** [comment]
Fixed in the latest release

**Comment by GGG-KILLER** [comment]
Seems to not be working still, I tried to log into MAL and it just redirects back to the app without it being signed in.
No toast notifications or anything.

And if I try to log in again, I get a 500 Server Error from MAL.

**Comment by jobobby04** [comment]
MAL is having issues

**Comment by dtantono** [comment]
Let's wait for a couple of days. if this still not working. then this is definitely something wrong and we can reopened this issue
