### ISSUE TITLE
Two-way sync to mirror tracking services progress in app

### ISSUE THREAD

**Issue by Lolen10** [jobobby04/TachiyomiSY#1074]
### Describe your suggested feature

Currently, the tracking sync feature operates in a one-way direction: from TachiyomiSY to the tracking services. By implementing a two-way sync (between TachiyomiSY and the tracking services), users can effortlessly synchronize their reading progress across multiple devices. An existing Tachiyomi fork already incorporates this functionality, which can be found at this link: https://github.com/Saud-97/TachiyomiS97.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[1.10.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fuck TachiyomiS97. They are a crap fork who removed limiters that Tachiyomi added to be nice to sources.

Also see #1005
