### ISSUE TITLE
Volume based Manga  tracking Option

### ISSUE THREAD

**Issue by Therealcrazyone** [jobobby04/TachiyomiSY#386]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/tag/1.7.0)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Some manga get catorized per volume instead of on a chapter by chapter basis. Currently the manga tracking only allows for chapter per chapter tracking. It would be nice if you could configure it whenever it's on a volume basis. 

Currently when you finish a volume and you have tracking on it will think that you've only finished a chapter instead if a full volume 

Here you see I finished Volume 5 
![Screenshot_20210717-162153_TachiyomiSY](https://user-images.githubusercontent.com/12501958/126040073-fceb3ec0-b87a-456d-9a11-3ec71e52ffd9.jpg)
But on Anilist it counts it as a chapter
![SmartSelect_20210717-162315_Chrome](https://user-images.githubusercontent.com/12501958/126040074-d4ba99a1-b504-455d-a7e6-2bad3f4ba158.jpg)
