### ISSUE TITLE
Mangadex chapter tracking resets to zero

### ISSUE THREAD

**Issue by lewdpatriot** [jobobby04/TachiyomiSY#496]
### Steps to reproduce

1. Read manga from mangadex.
2. Add tracking

### Expected behavior

Mangadex tracker should update the chapters as i read.

### Actual behavior

It briefly shows the number of chapter I'm in currently but then immediately resets to zero automatically. Even if I manually update the chapter number it resets.

### Crash logs

![Screenshot_2022-01-03-21-51-23-16_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/63286528/147956367-a6b9fb49-79c2-4511-9b60-df4c0da48794.jpg)

### Tachiyomi version

Preview 425

### Android version

Android 11

### Device

Realme 6i

### Other details

It is happening since release 425 I think. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Mangadex currently does not support chapter tracking so its currently disabled
