### ISSUE TITLE
Group by tracking not working

### ISSUE THREAD

**Issue by danielkadosh10** [jobobby04/TachiyomiSY#524]
### Steps to reproduce

updated to 1.8.1 from 1.7.0 

### Expected behavior

mangas that are tracked as on hold should be grouped together when grouping by tracking

### Actual behavior

they are grouped with the untracked mangas unlike the 1.7.0 where they had a separate page

### Tachiyomi version

1.8.1

### Android version

android 10

### Device

samsung 9s plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by pietroferretti** [comment]
+1 on this.

I did some very superficial reading of the code, so take this for what it's worth: maybe it's this snippet [here](https://github.com/jobobby04/TachiyomiSY/blob/4aa9cc3851e8cb0d0942ad788b712f51cc64e23c/app/src/main/java/eu/kanade/tachiyomi/data/track/TrackManager.kt#L64) that uses `R.string.paused` instead of `R.string.on_hold`, after [this commit](https://github.com/jobobby04/TachiyomiSY/commit/4aa9cc3851e8cb0d0942ad788b712f51cc64e23c).

**Comment by Smithienious** [comment]
Did the devs forget about this?

**Comment by jobobby04** [comment]
I think I have it fixed in the preview, let m,e know if its not

**Comment by Smithienious** [comment]
@jobobby04 I'm on r442. Dex, Mal and Ani all set to on hold but my entries are in not tracked group. Do I need a fresh install for this?

**Comment by jobobby04** [comment]
No, it must still be broken then

**Comment by pietroferretti** [comment]
As far as I can tell this is fixed in 1.8.4.

**Comment by hoang-himself** [comment]
Also working on r464.

**Comment by jobobby04** [comment]
Forgot to set this as fixed lol, thanks for the heads up
