### ISSUE TITLE
Tracking search options to: Include Novels (for Kitsu mainly), automatically remove () / [] brackets + contents, & use Japanese titles.

### ISSUE THREAD

**Issue by Kurogal** [jobobby04/TachiyomiSY#615]
### Describe your suggested feature

Kitsu has this issue where Doujinshi seem to be frequently categorized as Novels rather than anything else.

Using my list for examples:
https://kitsu.io/users/Kurogal/library?media=manga&title=novel

I have a few actual novels on there, but the overwhelming majority of the results are just miscategorized Doujinshi or Manga.
Picking out three examples:

Nyotaika Yankee Gakuen☆: Ore no Hajimete, Nerawaretemasu:
Manga: https://myanimelist.net/manga/89660
Manga: https://anilist.co/manga/104573/Nyotaika-Yankee-Gakuen-Ore-no-Hajimete-Nerawaretemasu/
Novel: https://kitsu.io/manga/nyotai-ka-yankee-gakuen-ore-no-hajimete-nerawaretemasu

Doutei Danshi Kousei Iinkai:
Manga: https://myanimelist.net/manga/103726
Manga: https://anilist.co/manga/100076/Doutei-Danshi-Kousei-Iinkai/
Novel: https://kitsu.io/manga/doutei-danshi-kousei-iinkai

Lilim's:
Manga: https://myanimelist.net/manga/103839 
Manga: https://anilist.co/manga/118247/Lilims/
Novel: https://kitsu.io/manga/lilim-s

Kitsu's user search page seems to only display up to 20 results at a time, but there's more beyond that on my list such as:

Itoshi no Oniisama: Lilim's Gaiden:
Manga: https://myanimelist.net/manga/103840
Manga: https://anilist.co/manga/118248/Itoshi-no-Oniisama-Lilims-Gaiden/
Novel: https://kitsu.io/manga/itoshi-no-oniisama-lilim-s-gaiden

---

Beyond handling Kitsu's categorization I  think it'd be worthwhile to have an option to add Novels to the tracking search for all platforms, since people upload actual novels onto e-hentai / exhentai , including Non-H novels.

https://e-hentai.org/?f_cats=545&f_search=other:novel%24%2C+-translated

https://e-hentai.org/g/2205758/55b3154f27/
https://anilist.co/manga/120344/Boku-no-Risou-no-Isekai-Seikatsu-Kemomimi-Bishoujo-Harem-de-Ecchi-na-Nichijou/

Though it probably won't be needed even if it's not optional to search for novels, it might also be worth highlighting "Type: Novel" or having some other kind of extra separation, either in general or at least when a Manga/Doujinshi of the same title exists.

---

I think it'd also be great if there was an option to automatically remove at least the `()` and `[]` brackets and their contents from the tracking search.
But not also the `{}` and `<>` brackets contents as the only setting.

Like in the title "[Noraneko-no-Tama (Yukino Minato)] Hikari no Kimi no Saganaki Keikaku `<Hikaru>` [Decensored] [Digital]",  I have to get rid of the `[]`, `()`, and their contents before Anilist search starts showing anything, but the `<Hikaru>` contained in the angled brackets is actually part of the title (even though the `<>` themselves aren't, it doesn't effect the search to include them) which makes it show up as the first result vs all the other doujins in the same series.

It wouldn't be a cure all, since in another example: "[Entelekheia (Chirumakuro)] Hinako Ikusei Nisshi Hinako ga Nyuugyuu ni Naru Made | Hinako Rearing Log - Hinako Becomes a Dairy Cow [English] [2019-01-16]"
I'd then have to delete everything down to either "Hinako Rearing Log" or the Romaji half of the title that's divided by `|` before it shows up, but it would be a nicer starting point.

The main issue there anyway there is unrelated to app itself, and instead with tracking sites like Anilist currently only having the English and Japanese main title for it and not the subtitle like the Romaji does.
https://anilist.co/manga/131178/Hinako-Ikusei-Nisshi/

But I also wanted to bring up the possibility of an option to use the Japanese title that e/exhentai and nhentai have on every translated gallery in the search on top of that.
So the Japanese title it has on ehentai: "[エンテレケイア (ちるまくろ)] ひなこ育成日誌 ひなこが乳牛になるまで [英訳] [2019年1月16日]" would be boiled down to "ひなこ育成日誌 ひなこが乳牛になるまで".
Even though in this case it still wouldn't work for Anilist without deleting the subtitle "ひなこが乳牛になるまで | Hinako Becomes a Dairy Cow", if Anilist did have the full title it'd work instantly without dealing with either the English and Romaji title first, and regardless it'd be less stuff to delete for database entries in a similar state.

### Other details

---
The primary reason I'm posting this here instead of upstream is that the Kitsu issue only really effects Doujinshi which I assume would be a minority of their users versus SY, and I doubt the average manga site vanilla Tachiyomi would be used with even offers actual novels like e/exhentai does.

And of course commercial Manga that were light novels like Danmachi is significantly more common so it would end up making a big mess there for very minimal benefit.

Detailed Acknowledgements:
1. TachiyomiSY's [contributor code of conduct](https://github.com/jobobby04/TachiyomiSY/blob/c4dfbd47685dc4701a5077c523e929bec1316629/CODE_OF_CONDUCT.md )  a GitHub popup wanted me to read before continuing says sexualized language, imagery, ect isn't allowed.
But while searching for similar issues to any of my feature requests which I didn't fine any of, I found at least one instance of a contributor linking directly to an e-hentai gallery  that wasn't Non-H which I'm avoiding linking solely to avoid the "referenced this issue" popup since it's a completely unrelated issue. So I assume this is fine and it's more of a, directed at other users kind of thing.

2. It's about a short as a title as I think it could without possibly losing too much of my intended meaning or missing what features I want.

3. As far as I'm aware tracking isn't handled by an extension, the brackets in the title effects e/exhentai and any sites that scrape it like nhentai, and the same with the Japanese titles, so it's not a single extension issue. 

4. The app itself says my Version is "Stable 1.8.3 (4/22/22 23:42) and checking for updates says I'm on the latest version.

5. This likely more on the side of being too much information rather than just the requested information, unless I've missed something obvious, but as far as I'm aware I gave about as much relevant info on each feature request as I reasonably could, this was a bit longer before I trimmed it a bit.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
You can ignore that section of code of conduct in this repo for external links, its there because of main Tachi, and I keep it if someone ever gets the idea to upload loli screenshots to github.

Cleaning titles is a good idea to do in general for E-Hentai and hentai sources. In the library selection menu there is a option to clean the titles of the selected manga, if they are from hentai sources like E-Hentai. You could use that before running the track search, but I get it if you dont since that would be an extra step after adding it to your library. A seperate option to do it before tracking may be useful because of that, not sure where I woud put it though.

I will consider the options for Kitsu, I am not keen on editing the tracking code because of the upkeep I would have to do when main Tachi it edits it. Personally I would like Kitsu to fix it since obviously they are not novels. But for actual novels on E-Hentai I see what you mean. I use EBook readers for my LNs so I wouldnt ever use tachi though, so it wouldnt be a priority.
