### ISSUE TITLE
Weird Tracking Behavior.

### ISSUE THREAD

**Issue by Mano5JP** [jobobby04/TachiyomiSY#618]
### Steps to reproduce

1. Go to any tracked series.
	1. Go to Tracking.
			
| HTTP error 404  										 | Could not find manga 										  |
| :---:   												 | :---:   														  |
|![TachiyomySY1](https://user-images.githubusercontent.com/64928088/173555135-5e09be44-ab76-4992-aa75-c0519e0ee043.jpg)| ![TachiyomySY2](https://user-images.githubusercontent.com/64928088/173555122-0e2719b8-63d0-4b29-a179-a855ef58983c.jpg) |
			
2. Read any tracked series
	1. Go to Tracking
		1. Anilist is tracking properly.
		2. MU is not tracking properly.

3. I didn't know what was causing issue. So,
			- I logout, clear cookies, Force close, re-login again from tracking services.
			- I used "Mercenary Teenage" to check; to removed and re-added tracking then there was no error.
			- Then I use other tracked series to check without changing it, i saw 404 error again. So, re-login didn't do much

	https://user-images.githubusercontent.com/64928088/173569650-082fe1f5-949a-42d1-9c3e-c2869343e8b4.mp4

### Expected behavior

After login out and relogging should have fix the problem

Anilist should stop showing 404.
MU should be tracking properly.

But Anilist still shows 404 and MU is not tracking properly.

### Actual behavior

If I don't remove and re-add tracking,
	- Anilist still shows error 404 and does track series.
	- MU shows no error but isn't tracking properly.

----

After removing and readding tracker, i can see there is no issue.

https://user-images.githubusercontent.com/64928088/173575525-6023d281-3d72-401e-8ff5-28b463457d3d.mp4

### Crash logs

NA

### Tachiyomi version

r485

### Android version

Android 12

### Device

Samsung Note 10+

### Other details

For me it looked 404 was causes by Anilist altho i am not totally sure, but even after relogin, issue persists. 
Now my only choice is to remove and re-add tracking again so, error 404 goes away.

But now I need to do for same for MU too as it isn't updating.

This isn't an issue with previous Pre-Main(r4446) and Latest Pre-Main(r4466).

Let me know, if this can be fix as soonest, otherwise i will start with the labour work.
As I am not sure what the issue yet. So, do let me know if i should separate the issue, if so, how?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
No idea, nothing between Tachi main and SY are different for Anilist and MangaUpdates

**Comment by Mano5JP** [comment]
Update:
Both Anilist and MangaUpdates are throwing error now.
Anilist: Could not found manga
MU: HTTP error 404


https://user-images.githubusercontent.com/64928088/173597389-f30b67bd-4552-4d68-8035-72f7d7a590b4.mp4

I might track separately on 2 non track series and check later again.

**Comment by Bobbysx** [comment]
I had exactly the same error, in the same version, with MAL.
Had to manually select again the manga in the list for it to work again.

**Comment by Mano5JP** [comment]
So, the one I removed and re-added tracker, has not shown any error. 

Which says I need to do the same for others.


Goodness gracious 😳 I need to do it for the 400+ series.

**Comment by Mano5JP** [comment]
What causes it idk? But my issue is resolved after I removed and then re-adding trackers.

Well, of course, I did only for my top reading list, and the latter remains the same with the above error.
 
So, Syer, you may close this or leave it as is. ✌️

**Comment by jobobby04** [comment]
Ill just close it then 😄 . No need for me to bother with weird tracking issues that are not caused by SY code
