### ISSUE TITLE
Tracking issue. 

### ISSUE THREAD

**Issue by kyoyacchi** [jobobby04/TachiyomiSY#646]
### Steps to reproduce

It says same "could not find manga" message for every manga when i click to "tracking" place. 
as far as i can see you have no intention to fix that bug. 

https://github.com/jobobby04/TachiyomiSY/issues/618#issuecomment-1169079183

It doesn't happen in TachiyomiAZ or TachiJ2K
I don't know why you're so sure about why it's not caused by SY.

https://user-images.githubusercontent.com/63583961/182117468-0660841f-404c-4516-8629-9f2d86f412f2.mp4

(I'll update video)

### Expected behavior

It shouldn't say "could not find manga" or "http error 404"

### Actual behavior

It says "could not find manga" for every manga whenever i click to tracking place.

### Crash logs

No crash logs.

### Tachiyomi version

1.8.4

### Android version

Android 11

### Device

Tecno Spark 7T

### Other details

It says HTTP ERROR 404 when i try to update or see MangaDex Tracker.
I believe #618 explains better.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
Isn't Mangadex tracking broken? As in on the website. Also Az and j2k don't have mangadex tracker, right?

I don't know why sy have Mangadex tracking enabled if it doesn't work. It should be disable to prevent confusion

**Comment by jobobby04** [comment]
> I don't know why you're so sure about why it's not caused by SY.

Because SY doesnt edit any of the relavent tracking code, its all from main Tachi. I have no interest in tracking so it doesnt have anything extra.

> Isn't Mangadex tracking broken

Its half working, you cant update your chapter progress, but you can add it to your tracking lists.

`could not find manga` is an error with the Kitsu or the Anilist trackers, maybe try relogging one those

`HTTP ERROR 404` Could happen for any reason, I need logs to be able to determine why. Maybe try re-logging that as well.

I am going to close this as most of it isnt SY specific errors, if the logs indicate that the HTTP Error 404 errror is a SY issue I'll open it again(send me it in dm if it gets locked).
