### ISSUE TITLE
MangaDex tracker doesn't update chapter count

### ISSUE THREAD

**Issue by kyoyacchi** [jobobby04/TachiyomiSY#647]
### Steps to reproduce

Try selecting a chapter number.
Then click ok
Go to manga page, then go to tracker page back.

https://user-images.githubusercontent.com/63583961/182122185-73967fc7-970a-4a16-9858-39f5c5cc88b8.mp4

### Expected behavior

It should set it as how i set 

### Actual behavior

It reverts back to 0

### Tachiyomi version

1.8.4

### Android version

Android 11

### Device

Tecno Spark 7T

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Known limitation with the Mangadex api. Can't do anything about it for now
