### ISSUE TITLE
Add the score of manga when one tries to add an entry for the tracker

### ISSUE THREAD

**Issue by Palloxin** [jobobby04/TachiyomiSY#708]
### Describe your suggested feature

![immagine](https://user-images.githubusercontent.com/75091899/197401748-7b13e9cd-e1a2-4e15-b1c3-8051e9d86682.png)
add here the average score of Anilist. i am proposing this because when I want to start a new hentai i would like to see the score of the said hentai (see the image) there( if it exist) so that we are not obliged to open in the browser (entries in anilist) and check the score, so of course this is a QoL suggestion.
i proposed only anilist because:
1. Mal doesn't accept entries of any hentai easly specially pornhwas (manhwa hentai), so their archive is poor on this category
2. i didn't try myself other webisites avaiable on tachi, so **maybe**, if they are fine too like anilist, add the score thing there too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I personally am not interested in this, you could open a issue in the main Tachi repo and SY would would get it if main Tachi does.
