### ISSUE TITLE
MangaUpdates tracker

### ISSUE THREAD

**Issue by edmxn** [jobobby04/TachiyomiSY#726]
### Describe your suggested feature

Add MangaUpdates website as tracker

### Other details

already in 'Tachiyomi'

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Already in the preview build

**Comment by edmxn** [comment]
> Already in the preview build

Is there a way to return the customization of everything to the previous version? this new version has too much lag

**Comment by jobobby04** [comment]
Nope

**Comment by edmxn** [comment]
> Nope

And any way to add MangaUpdates as a tracker to the previous version?

**Comment by jobobby04** [comment]
I'm not doing it, so unless you fork SY and do it, nope.

**Comment by edmxn** [comment]
> I'm not doing it, so unless you fork SY and do it, nope.

Uh... I understand, sorry, one more thing, the app closes in the middle of the library update, this doesn't happen to me in Tachiyomi 🤔

**Comment by jobobby04** [comment]
I would suggest joining the https://discord.gg/Tachiyomi discord for help with that
