### ISSUE TITLE
Mangadex tracker not working for other sources

### ISSUE THREAD

**Issue by Rubberxgum** [jobobby04/TachiyomiSY#874]
### Steps to reproduce

1. Open a manga from sources other than Mangadex.
2. Press Tracking
3. Select Mangadex
4. Press the manga from the Mangadex tracker
5. Press track

### Expected behavior

Mangadex tracker would be registered as a tracker for that manga.

### Actual behavior

Mangadex tracker doesn't get registered and there's a prompt saying "HTTP error 401".

### Crash logs
```
--------- beginning of main
04-30 21:08:43.378 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:08:43.494 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:08:45.306 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: Failed to refresh track data mangaId=1279 for service 60
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: eu.kanade.tachiyomi.network.HttpException: HTTP error 401
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	at exh.md.service.MangaDexAuthService.readingStatusForManga(MangaDexAuthService.kt:87)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	at exh.md.handlers.FollowsHandler$fetchTrackingInfo$2$followStatusDef$1.invokeSuspend(FollowsHandler.kt:39)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 	Suppressed: eu.kanade.tachiyomi.network.HttpException: HTTP error 401
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 		at exh.md.service.MangaDexAuthService.mangasRating(MangaDexAuthService.kt:99)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 		at exh.md.handlers.FollowsHandler$fetchTrackingInfo$2$ratingDef$1.invokeSuspend(FollowsHandler.kt:38)
04-30 21:08:53.532 22485 22485 E TrackInfoDialogHomeScreen: 		... 6 more
04-30 21:08:53.602 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:08:54.339 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:08:55.757 22485 22485 E TrackInfoDialogHomeScreen: Failed to refresh track data mangaId=1279 for service 7
04-30 21:08:55.757 22485 22485 E TrackInfoDialogHomeScreen: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@c2ae67b
04-30 21:08:55.759 22485 22485 E TrackInfoDialogHomeScreen: Failed to refresh track data mangaId=1279
04-30 21:08:55.759 22485 22485 E TrackInfoDialogHomeScreen: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@c2ae67b
04-30 21:09:23.978 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:10:23.987 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:10:25.637 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:10:28.388 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:10:42.479 22485 23357 E DatabaseUtils: Writing exception to parcel
04-30 21:10:42.479 22485 23357 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25121, uid=1000 requires the provider be exported, or grantUriPermission()
04-30 21:10:42.479 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
04-30 21:10:42.479 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
04-30 21:10:42.479 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
04-30 21:10:42.479 22485 23357 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
04-30 21:10:42.479 22485 23357 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
04-30 21:10:42.479 22485 23357 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
04-30 21:10:42.509 22485 23357 E DatabaseUtils: Writing exception to parcel
04-30 21:10:42.509 22485 23357 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25121, uid=1000 requires the provider be exported, or grantUriPermission()
04-30 21:10:42.509 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
04-30 21:10:42.509 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
04-30 21:10:42.509 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
04-30 21:10:42.509 22485 23357 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
04-30 21:10:42.509 22485 23357 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
04-30 21:10:42.509 22485 23357 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
04-30 21:10:42.565 22485 23357 E DatabaseUtils: Writing exception to parcel
04-30 21:10:42.565 22485 23357 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.sy.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=25121, uid=1000 requires the provider be exported, or grantUriPermission()
04-30 21:10:42.565 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
04-30 21:10:42.565 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
04-30 21:10:42.565 22485 23357 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
04-30 21:10:42.565 22485 23357 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
04-30 21:10:42.565 22485 23357 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
04-30 21:10:42.565 22485 23357 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
04-30 21:11:05.852 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
04-30 21:11:07.641 22485 22529 E OpenGLRenderer: Unable to match the desired swap behavior.
App version: 1.9.3 (standard, 18d3615, 50, 2023-04-18T21:33Z)
Preview build: 0
Android version: 13 (SDK 33)
Android build ID: TQ2A.230405.003
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sunny
Device model: M2101K7AG
Device product name: sunny_global
```
### Tachiyomi version

1.9.3

### Android version

Android 13

### Device

Redmi Note 10

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
It works fine for me, try re-logging mangadex
