### ISSUE TITLE
Suggested tracking date

### ISSUE THREAD

**Issue by Rubberxgum** [jobobby04/TachiyomiSY#909]
### Describe your suggested feature

 Some tracking services such as Anilist tracks the date when you started reading a manga and when you finished it. On Neko, when you click the "started reading date", it gives you a suggested date which I think is based on your history. 

 This feature is very convenient as you don't have to know the date and manually type it every time you starts reading a manga. It also remembers the date when you starts reading a manga so you wouldn't have to worry about forgetting to track the "started reading date" on the day that you started reading a manga.

![Screenshot_20230703-060056~2](https://github.com/jobobby04/TachiyomiSY/assets/90501519/5afb908e-a09f-47c4-a27b-4839e557c024)

### Other details

In TachiJ2K, when you already started reading a manga, Anilist would automatically track the date instead of suggesting it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Personally not interested in this, I don't use tracking. Open a issue with main Tachi and SY will get it if Main Tachi does.
