### ISSUE TITLE
Cannot login to anilist tracker

### ISSUE THREAD

**Issue by LoneWolf993** [jobobby04/TachiyomiSY#965]
### Steps to reproduce

1. Go to tracking option in tachiyomisy settings
2. Click on anilist and try to login

### Expected behavior

It should be successfully logged in.

### Actual behavior

The app seems to crash and the login fails.

### Crash logs

--------- beginning of main
10-16 09:44:45.116 29256 29326 E OpenGLRenderer: Unable to match the desired swap behavior.
10-16 09:44:45.311 29256 29471 E SQLiteLog: (284) automatic index on C(manga_id)
10-16 09:44:45.311 29256 29471 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-16 09:44:45.366 29256 29471 E SQLiteLog: (284) automatic index on C(manga_id)
10-16 09:44:45.366 29256 29471 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-16 09:44:45.366 29256 29471 E SQLiteLog: (284) automatic index on merged(manga_id)
10-16 09:44:45.366 29256 29471 E SQLiteLog: (284) automatic index on ME(merge_id)
10-16 09:44:45.366 29256 29471 E SQLiteLog: (284) automatic index on C(merge_id)
10-16 09:44:45.366 29256 29471 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-16 09:44:51.078 29256 29461 E SQLiteLog: (284) automatic index on ME(merge_id)
10-16 09:45:38.409 29256 29326 E OpenGLRenderer: Unable to match the desired swap behavior.
10-16 09:45:39.179 29256 29326 E OpenGLRenderer: Unable to match the desired swap behavior.
10-16 09:45:43.156 29256 29326 E OpenGLRenderer: Unable to match the desired swap behavior.
10-16 09:45:43.260 29256 29326 E OpenGLRenderer: Unable to match the desired swap behavior.
10-16 09:45:51.053 29256 29326 E OpenGLRenderer: Unable to match the desired swap behavior.
10-16 09:45:53.637 29256 29326 E OpenGLRenderer: Unable to match the desired swap behavior.
10-16 09:45:53.770 29256 29326 E OpenGLRenderer: Unable to match the desired swap behavior.
App version: 1.9.3 (standard, 18d3615, 50, 2023-04-18T21:33Z)
Preview build: 0
Android version: 13 (SDK 33)
Android build ID: T3TC33.18-48-6
Device brand: motorola
Device manufacturer: motorola
Device name: bangkk
Device model: moto g84 5G
Device product name: bangkk_g

### Tachiyomi version

1.9.3

### Android version

Android 13

### Device

Motorola moto g84 5g

### Other details

https://github.com/jobobby04/TachiyomiSY/assets/66156681/2005147d-cffa-4878-a331-7390eda57f04

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by KMohZaid** [comment]
Same issue, and I guess it is in anilist token login method, shikimori login worked and MAL is on maintenance so I don't know about it

But still seems anilist method has this issue only (maybe there is change in response anilist give)

https://github.com/jobobby04/TachiyomiSY/blob/d37463cf0f091ade15fa80c7b75fe378a45eee61/app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt#L210

**Comment by LoneWolf993** [comment]
> Same issue, and I guess it is in anilist token login method, shikimori login worked and MAL is on maintenance so I don't know about it
> 
> But still seems anilist method has this issue only (maybe there is change in response anilist give)
> 
> https://github.com/jobobby04/TachiyomiSY/blob/d37463cf0f091ade15fa80c7b75fe378a45eee61/app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt#L210-L220

Yea, It seems anilist has recently changed something because I have been using the anilist tracker for quite a while and didn't face any problems before today

**Comment by KMohZaid** [comment]
> > Same issue, and I guess it is in anilist token login method, shikimori login worked and MAL is on maintenance so I don't know about it
> > But still seems anilist method has this issue only (maybe there is change in response anilist give)
> > https://github.com/jobobby04/TachiyomiSY/blob/d37463cf0f091ade15fa80c7b75fe378a45eee61/app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt#L210-L220
> 
> Yea, It seems anilist has recently changed something because I have been using the anilist tracker for quite a while and didn't face any problems before today

yes, i check response fragment and it is same as old, ig it is api related change but not announce yet

btw i dont know much of kotlin yet so not going deep dive into it yet lol, + haven't use anilist api myself

**Comment by KMohZaid** [comment]
this is due to api change of anilist, i tried tachiJ2K and other forks, all have same issue

**Comment by jobobby04** [comment]
> The AniList API is currently down. Tracking and the ability to log in to it won't work until it's back up.

**Comment by KMohZaid** [comment]
> > The AniList API is currently down. Tracking and the ability to log in to it won't work until it's back up.

Yeah I thought that but when try to use graphql, it works. Ig user auth based api down.

> Btw this Issue not closed completely as I was able to comment
