### ISSUE TITLE
Merged manga Tracking issue

### ISSUE THREAD

**Issue by Riztard** [jobobby04/TachiyomiSY#976]
### Steps to reproduce

1. merge manga
2. read unread chapter

### Expected behavior

tracked chapter should be increased

### Actual behavior

tracked chapter doesnt change

### Tachiyomi version

r532

### Android version

A13

### Device

Redmi 8

### Other details

seems like need to add the tracker to the individual source(tracking each)
maybe just copy the tracker to another while merging

![image](https://github.com/jobobby04/TachiyomiSY/assets/16263232/7240062d-752c-4e1a-9706-0d7a53d934ea)

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.4](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.
